### ISSUE TITLE
Left/Right Shoulders different

### ISSUE THREAD

**Issue by evanwyatt** [Jerome-Graves/yertle#5]
It looks like the left and right shoulder STLs are different designs, the left shoulder looks to be an older design? The right shoulder matches the CAD.

Are you able to confirm the left shoulder should just be mirror of the right shoulder?

**Comment by Jerome-Graves** [comment]
Thanks, I've accidentally added the bearing to the stl file. I will fix this now

**Comment by Jerome-Graves** [comment]
[https://github.com/Jerome-Graves/yertle/commit/4d145622e7d98a33851c681c44f7bdecb39f5b37](fixed)

**Comment by evanwyatt** [comment]
Thanks, I thought it looked like a bearing!
