### ISSUE TITLE
Outer Shoulder Frame probably contains bearings

### ISSUE THREAD

**Issue by pmoliterni** [Jerome-Graves/yertle#9]
The STL file "Outer Shoulder Frame" probably contains bearings. Is it that correct ?

**Comment by Jerome-Graves** [comment]
Yes, I will fix this now.

**Comment by Jerome-Graves** [comment]
#

**Comment by Jerome-Graves** [comment]
> The STL file "Outer Shoulder Frame" probably contains bearings. Is it that correct ?

This was an error, and I have removed the bearings from the file.
